version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  event-service:
    build:
      context: ./ie.atu.project.cicd_project/EventMicroService
      dockerfile: Dockerfile
    ports:
      - "8085:8080"

  inventory-service:
    build:
      context: ./ie.atu.project.cicd_project/InventoryMicroService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  member-service:
    build:
      context: ./ie.atu.project.cicd_project/MemberMicroService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  ranking-service:
    build:
      context: ./ie.atu.project.cicd_project/RankingMicroService
      dockerfile: Dockerfile
    ports:
      - "8083:8080"

  training-session-service:
    build:
      context: ./ie.atu.project.cicd_project/TrainingSessionMicroService
      dockerfile: Dockerfile
    ports:
      - "8084:8080"

  h2-database:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "81:81"
    volumes:
      - h2-data:/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists

volumes:
  db-data:
  h2-data:
