version: '3.8'

services:

  event-service:
    build:
      context: ./ie.atu.project.cicd_project/EventMicroService
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    networks:
      - bjj-network

  inventory-service:
    build:
      context: ./ie.atu.project.cicd_project/InventoryMicroService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - bjj-network

  member-service:
    build:
      context: ./ie.atu.project.cicd_project/MemberMicroService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - bjj-network

  ranking-service:
    build:
      context: ./ie.atu.project.cicd_project/RankingMicroService
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    networks:
      - bjj-network

  training-session-service:
    build:
      context: ./ie.atu.project.cicd_project/TrainingSessionMicroService
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    networks:
      - bjj-network
networks:
  bjj-network:
    driver: bridge
